import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillInstagram, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import Image from "next/image";
import profile from '../public/profile.png';
import profile2 from '../public/profile2.png';
import { FcBriefcase, FcMultipleDevices, FcParallelTasks } from 'react-icons/fc';
import web1 from '../public/when2meet.png';
import web2 from '../public/winno.png';
import web3 from '../public/development.png';
import Typical from 'react-typical';
import {Link} from 'react-scroll';
import { useState } from 'react';

export default function Home() {

  const [darkMode, setDarkMode] = useState(true)

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[#FFFFFF] px-10 md:px-20 lg:px-30 dark:bg-[#222222]">
        <section>
          <nav className="py-10 mb-12 flex justify-between">
            <ul className="flex items-center">
              <li>
                <Link to="about" spy={true} smooth={true} offset={-15} duration={500} className="cursor-pointer hover:text-[#553939] dark:hover:text-[#E3CAA5] px-3 text-xl dark:text-[#F8EDE3]">About Me</Link>
              </li>
              <li>
                <Link to="services" spy={true} smooth={true} offset={-15} duration={500} className="cursor-pointer hover:text-[#553939] dark:hover:text-[#E3CAA5] px-3 text-xl dark:text-[#F8EDE3]">Languages</Link>
              </li>
              <li>
                <Link to="portfolio" spy={true} smooth={true} offset={-15} duration={500} className="cursor-pointer hover:text-[#553939] dark:hover:text-[#E3CAA5] px-3 text-xl dark:text-[#F8EDE3]">Portfolio</Link>
              </li>
            </ul>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="dark:text-[#FFFFFF] dark:hover:text-[#E3CAA5] hover:text-[#553939] cursor-pointer text-2xl"/></li>
              <li><a className="bg-[#553939] dark:text-[#000000] dark:bg-[#F8EDE3] text-white px-4 py-2 rounded-md ml-8 dark:hover:bg-[#E3CAA5] hover:bg-[#F8EDE3]" 
                     href="#"
                  >
                    Resume
                  </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-5xl py-2 text-[#553939] dark:text-[#FFFFFF] font-medium md:text-7xl">lazyelephant420</h2>
            <h3 className="text-2xl text-[#161925] py-2 md:text-3xl dark:text-[#f2e5d9]">
              <Typical
                loop={Infinity}
                wrapper="p"
                steps={[
                  'developer & designer',
                  1000,
                ]}
            />
            </h3>
            {/* if you want to put a description down below */}
            {/* <p className="text-md py-2 leading-8 text-[#161925] md:text-md max-w-md mx-auto"></p> */}
          </div>
          <div className="dark:from-[#f2e5d9] relative mx-auto bg-gradient-to-b from-[#553939] rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96">
            <Image className="scale-90" src={profile2} layout="fill" objectFit="cover"/> 
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 mt-6 text-gray-600">
            <a target="_blank" href="https://www.instagram.com/sedong_hwang/?hl=en"><AiFillInstagram className="text-[#553939] dark:text-[#F8EDE3]"/></a>
            <a target="_blank" href="https://www.linkedin.com/in/sedonghwang/"><AiFillLinkedin className="text-[#0072b1] dark:text-[#F8EDE3]"/></a>
            <a target="_blank" href="https://www.youtube.com/watch?v=6-QREG_u084"><AiFillYoutube className="text-[#FF0000] dark:text-[#F8EDE3]"/></a>
          </div>
        </section>
      
        <section id="about">
          <div className="mt-5">
            <h3 className="text-3xl py-1 dark:text-[#FFFBE9]">About me</h3>
            <div className="text-md mt-1 py-2 leading-7 text-gray-800 dark:text-[#FFFBE9]">
              <p>
                Hi wonderful people 👋, 
              </p>
              <p>
                My name is lazyelephant420 and I am a current junior at Brown University. I thrive under a good challenge and love to experiment with
                frontend development. When I'm not coding, I like to read 📚, play basketball 🏀, practice my cello 🎶, watch youtube 🧑🏻‍💻, or eat out with friends 🥂.
              </p>
            </div>
          </div>
        </section>

        <section id="services">
          <div className="mt-5">
            <h3 className="text-3xl py-1 dark:text-[#FFFBE9]">Programming Languages</h3>
            <div className="lg:flex gap-10">
              <div className="bg-[#f2e5d9] dark:bg-[#434242] flex-1 text-center shadow-xl p-10 rounded-xl my-5">
                <FcMultipleDevices className="w-28 h-28 relative mx-auto"/>
                <h3 className="text-lg mt-2 font-medium pb-2 dark:text-[#FFFFFF]">Frontend</h3>
                <p className="py-2 dark:text-[#f2e5d9]">Building beautiful web applications</p>
                <h4 className="py-4 text-[#553939] dark:text-[#22A39F]">Languages</h4>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">HTML</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">CSS</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">JavaScript</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">React/React-Native</p>
              </div>
              <div className="bg-[#f2e5d9] dark:bg-[#434242] flex-1 text-center shadow-xl p-10 rounded-xl my-5">
                {/* <Image src={code} className="w-28 h-28 relative mx-auto"/> */}
                <FcBriefcase className="w-28 h-28 relative mx-auto"/>
                <h3 className="text-lg mt-2 font-medium pb-2 dark:text-[#FFFFFF]">Backend</h3>
                <p className="py-2 dark:text-[#f2e5d9]">Connecting safe & secured data</p>
                <h4 className="py-4 text-[#553939] dark:text-[#22A39F]">Languages</h4>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">MySQL</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">Java</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">FireBase</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">API</p>
              </div>
              <div className="bg-[#f2e5d9] dark:bg-[#434242] flex-1 text-center shadow-xl p-10 rounded-xl my-5">
                <FcParallelTasks className="w-28 h-28 relative mx-auto"/>
                <h3 className="text-lg mt-2 font-medium pb-2 dark:text-[#FFFFFF]">Frameworks/Design</h3>
                <p className="py-2 dark:text-[#f2e5d9]">Creating elegant designs suited for your needs</p>
                <h4 className="py-4 text-[#553939] dark:text-[#22A39F]">Languages</h4>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">Figma</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">Bootstrap/Tailwind</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">Github Desktop</p>
                <p className="text-gray-800 py-1 dark:text-[#f2e5d9]">Balsamiq</p>
              </div>
            </div>
          </div>
        </section>
        <section id="portfolio">
          <div>
            <h3 className="text-3xl py-1 dark:text-[#ffffff]">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-[#f2e5d9]">
              Since the beginning of my journey as a developer, I've done remote work for startups
              and collaborated with talented peers at Brown to create digital products
              for consumer use.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web1} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web2} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive" src={web3} />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
